// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp.Data;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace MyApp.Migrations
{
    [DbContext(typeof(MyAppContext))]
    [Migration("20250823190728_Migration-5")]
    partial class Migration5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyApp.Models.Category", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("CATEGORY_TAB", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1m,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2m,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 3m,
                            Name = "Books"
                        });
                });

            modelBuilder.Entity("MyApp.Models.Client", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("CLIENT_TAB", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1m,
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2m,
                            Name = "Jane Doe"
                        });
                });

            modelBuilder.Entity("MyApp.Models.Item", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<decimal?>("CategoryId")
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("CATEGORY_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("NAME");

                    b.Property<decimal>("Price")
                        .HasColumnType("NUMBER")
                        .HasColumnName("PRICE");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ITEM_TAB", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1m,
                            CategoryId = 1m,
                            Name = "Microphone",
                            Price = 40m
                        });
                });

            modelBuilder.Entity("MyApp.Models.ItemClient", b =>
                {
                    b.Property<decimal>("ItemId")
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("ITEM_ID");

                    b.Property<decimal>("ClientId")
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("CLIENT_ID");

                    b.HasKey("ItemId", "ClientId");

                    b.HasIndex("ClientId");

                    b.ToTable("ITEM_CLIENT_TAB", (string)null);

                    b.HasData(
                        new
                        {
                            ItemId = 1m,
                            ClientId = 1m
                        });
                });

            modelBuilder.Entity("MyApp.Models.SerialNumber", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"));

                    b.Property<decimal>("ItemId")
                        .HasColumnType("NUMBER(38,0)")
                        .HasColumnName("ITEM_ID");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(100)")
                        .HasColumnName("NUMBER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("SERIAL_NUMBER_TAB", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1m,
                            ItemId = 1m,
                            Number = "MIC150"
                        });
                });

            modelBuilder.Entity("MyApp.Models.Item", b =>
                {
                    b.HasOne("MyApp.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MyApp.Models.ItemClient", b =>
                {
                    b.HasOne("MyApp.Models.Client", "Client")
                        .WithMany("ItemClients")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApp.Models.Item", "Item")
                        .WithMany("ItemClients")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("MyApp.Models.SerialNumber", b =>
                {
                    b.HasOne("MyApp.Models.Item", "Item")
                        .WithOne("SerialNumber")
                        .HasForeignKey("MyApp.Models.SerialNumber", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("MyApp.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MyApp.Models.Client", b =>
                {
                    b.Navigation("ItemClients");
                });

            modelBuilder.Entity("MyApp.Models.Item", b =>
                {
                    b.Navigation("ItemClients");

                    b.Navigation("SerialNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
